# -*- coding: utf-8 -*-
"""plan of action

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1orFlByUsPD1rBJ1wE2eJWXFG5wZTnviv
"""

from google.colab import drive
drive.mount("/content/gdrive", force_remount=True)

import openai

# Set your OpenAI API key
openai.api_key = 'YOUR_OPENAI_API_KEY'  # Replace with your OpenAI API key

# Read the transcript
input_path = r'/content/gdrive/My Drive/meet/transcription_translated.txt'
with open(input_path, 'r') as file:
    transcript = file.read()

# Prompt for the plan of action
prompt = (
    "Based on the following transcript of a meeting, generate a clear and actionable plan:\n\n"
    f"{transcript}\n\n"
    "Please provide the plan of action in bullet points."
)

# Call the OpenAI API to generate the plan of action
response = openai.ChatCompletion.create(
    model="gpt-3.5-turbo",
    messages=[
        {"role": "user", "content": prompt}
    ],
    max_tokens=300  # You can adjust the token limit based on your needs
)

plan_of_action = response['choices'][0]['message']['content']
print("Plan of Action:\n")
print(plan_of_action)

# Save the plan of action to a text file
output_path = r'/content/gdrive/My Drive/meet/plan_of_action.txt'
with open(output_path, 'w') as file:
    file.write(plan_of_action)

print(f"\nPlan of action saved to {output_path}.")