# -*- coding: utf-8 -*-
"""anotate speakers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JR4SRLXN7jmqCcjRbA80rNhnt5pUapdo
"""

from google.colab import drive
drive.mount("/content/gdrive")

!pip install pydub

#converting mp3 to wav (to use with pyannote)
from pydub import AudioSegment
sound = AudioSegment.from_mp3(r"/content/gdrive/My Drive/ytdl/testconv.mp3")
sound.export(r"/content/gdrive/My Drive/ytdl/testconv.wav", format="wav")

!pip install pyannote.audio

from pyannote.audio import Pipeline

pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization-3.1",use_auth_token="use your key")
# Perform diarization (detect number of speakers)
diarization = pipeline(r"/content/gdrive/My Drive/ytdl/testconv.wav")

# Print detected speakers
for turn, _, speaker in diarization.itertracks(yield_label=True):
    print(f"Speaker {speaker}: from {turn.start:.1f}s to {turn.end:.1f}s")