# -*- coding: utf-8 -*-
"""audio to transcribe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UpBz4kKyxuJcDTLpgEnmIq74Ijy-fUFI
"""

from google.colab import drive
drive.mount("/content/gdrive")

#Specific to google colab ignore if you are not using google colab.

!pip install openai==0.28 #use version below 1.0.0

import subprocess
import os
import openai

openai.api_key = input()

if not openai.api_key:
    raise ValueError("Error: OpenAI API key not found.")

# Function to extract audio from video using ffmpeg
def extract_audio_from_video(video_file, output_audio_file):
    command = [
        'ffmpeg',
        '-i', video_file, # video input
        '-q:a', '0', # audio quality setting
        '-map', 'a', # audio extraction
        output_audio_file # audio output
    ]
    try:
        subprocess.run(command, check=True)
        print(f"Audio extracted successfully")
    except subprocess.CalledProcessError:
        print("Error: Audio extraction failed.")
    except FileNotFoundError:
        print("Error: FFmpeg not found.")

# Function to transcribe audio using OpenAI Whisper
def transcribe_audio_with_whisper(audio_file):
    try:
        # Upload and transcribe audio using Whisper model
        with open(audio_file, "rb") as audio:
            print("Transcribing given audio, please wait...")
            transcription = openai.Audio.transcribe("whisper-1", audio)
            print("Transcripted Successfully.")
            return transcription["text"]
    except Exception as e:
        print(f"Error during transcription: {e}")
        return None

if __name__ == "__main__":
    # Get user inputs
    video_file = input("Enter video file path : ") #eg: /content/gdrive/My Drive/ytdl/forest.mp4
    audio_name = input("Enter output audio file name  (only filename, don't include extension) : ") #eg: forestaud
    audio_format = input("Enter audio format : ") #eg: mp3
    output_location = input("Enter the folder path to save the audio file and Transcript : ")  #eg: /content/gdrive/My Drive/ytdl

    #Saving the audio file in desired folder (/content/gdrive/My Drive/ytdl/forestaud.mp3)
    output_audio_file = os.path.join(output_location, f"{audio_name}.{audio_format}")

    # Step 1: Extract audio from the video
    extract_audio_from_video(video_file, output_audio_file)

    # Step 2: Transcribe the extracted audio using Whisper
    transcript = transcribe_audio_with_whisper(output_audio_file)

    # Step 3: Save the transcription text file if transcription was successful
    if transcript:
        transcript_file = os.path.join(output_location, f"{audio_name}_transcript.txt")
        with open(transcript_file, "w") as file:
            file.write(transcript)
        print(f"Transcription saved to: {transcript_file}")