# -*- coding: utf-8 -*-
"""translation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1orFlByUsPD1rBJ1wE2eJWXFG5wZTnviv
"""

from google.colab import drive
drive.mount("/content/gdrive", force_remount=True)

!pip install openai

!pip install git+https://github.com/openai/whisper.git
import whisper

model = whisper.load_model("large")

result = model.transcribe(r'/content/gdrive/My Drive/meet/meeting2.wav')
print(result["text"])

with open(r'/content/gdrive/My Drive/meet/transcription_output.txt', "w") as text_file:
    text_file.write(result["text"])

!pip install googletrans==4.0.0-rc1

from googletrans import Translator
import re

translator = Translator()

def translate_non_english(text):
    if not text:  # Check for empty input
        print("No text provided for translation.")
        return ""

    # Split the text into sentences
    sentences = re.split(r'(?<=[.!?]) +', text)
    translated_text = []

    for sentence in sentences:
        if not sentence.strip():  # Skip empty sentences
            continue
        lang = translator.detect(sentence).lang
        if lang != 'en':
            try:
                translated = translator.translate(sentence, dest='en').text
                translated_text.append(translated)
            except:
                # Skip translation if there's an error
                continue
        else:
            translated_text.append(sentence)

    return ' '.join(translated_text)

input_file_path = r'/content/gdrive/My Drive/meet/transcription_output.txt'
output_file_path = r'/content/gdrive/My Drive/meet/transcription_translated.txt'

try:
    with open(input_file_path, 'r', encoding='utf-8') as file:
        content = file.read()

    translated_content = translate_non_english(content)

    # Save the translated content to a new text file
    with open(output_file_path, 'w', encoding='utf-8') as file:
        file.write(translated_content)

    #Print statement
    print("Original Text:")
    print(content)
    print("\nTranslated Text:")
    print(translated_content)

    print(f"\nTranslated content saved to: {output_file_path}")

except FileNotFoundError:
    print(f"Error: The file {input_file_path} was not found.")
except Exception as e:
    print(f"An error occurred: {e}")